[project]
name = "ayon-usd-resolver"
version = "0.1.0"
description = "USD Asset Resolver for AYON"
authors = [
    { name="YNPUT Team", email = "team@ynput.io" }
]
license = "Apache 2"
readme = "README.md"
requires-python = ">=3.11,<3.14"

dependencies = [
    "pre-commit>=4.6.0",
    "codespell>=2.4.2",
    "cpplint>=2.0.2",
    "ruff>=0.15.20",
    "pytest>=9.1.1"
]

[tool.codespell]
ignore-words-list = "ayon,master,usd"
skip = "./.*,./ext/*"
count = true
quiet-level = 3
