[project]
name = "ayon-usd-resolver"
version = "0.1.0"
description = "USD Asset Resolver for AYON"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "YNPUT Team", email = "team@ynput.io" }]
license = { text = "Apache-2.0" }

[dependency-groups]
dev = [
	"cmakelang[yaml]>=0.6.13,<0.7.0",
	"codespell>=2.2.6,<3.0.0",
	"cpplint>=1.6.1,<2.0.0",
	"exceptiongroup==1.2.2",
	"iniconfig==2.0.0",
	"packaging==24.2",
	"pluggy==1.5.0",
	"pre-commit>=3.6.2,<4.0.0",
	"pytest==8.3.3",
	"tomli==2.2.1",
	"types-usd==24.5.2",
    "pytest",
    "pytest-ayon @ git+https://github.com/ynput/pytest-ayon.git",
]

[tool.uv]
package = false

[tool.codespell]
ignore-words-list = "ayon,master,usd"
skip = "./.*,./ext/*"
count = true
quiet-level = 3
