[project]
name = "ayon-usd-resolver"
version = "0.1.0"
description = "USD Asset Resolver for AYON"
authors = [
    { name="YNPUT Team", email = "team@ynput.io" }
]
license = "Apache 2"
readme = "README.md"
requires-python = ">=3.11"

[dependency-groups]
dev = [
	"codespell>=2.4.1",
	"cpplint>=2.0.2",
	"pre-commit>=4.6.0",
	"pytest>=9.1.1",
	"types-usd==24.5.2",
    "pytest-ayon @ git+https://github.com/ynput/pytest-ayon.git",
	"ruff>=0.15.20"
]

[tool.uv]
package = false

[tool.codespell]
ignore-words-list = "ayon,master,usd"
skip = "./.*,./ext/*"
count = true
quiet-level = 3
