name: Enhancement Request
description: Create a report to help us enhance a particular feature
title: "[enhancement]_Title"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue with this?
      description: Please search to see if an issue with the bug you encountered already exists.
      options:
      - label: I have searched the existing issues.
        required: true
  - type: textarea
    id: related-feature
    attributes:
      label: Please describe the feature you have in mind and the current shortcomings?
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal
    attributes:
      label: How would you imagine the implementation of the feature?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Are there any labels you wish to add?
      description: Please search labels and identify those related to your enhancement.
      options:
      - label: I have added the relevant labels to the enhancement request.
        required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered:"
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context:"
      description: Add any other context or screenshots about the enhancement request here.
    validations:
      required: false

