name: "Performance Issue/Security Vulnerability"
description: "Report performance issues or security vulnerabilities."
title: "[Performance Issue/Security Vulnerability]_Title "
labels: ["bug", "security"]
body:
  - type: markdown
    attributes:
      value: |
        **Please provide the following information:**

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the issue in detail."
      placeholder: "Detailed description of the issue."

  - type: textarea
    id: impact
    attributes:
      label: "Impact"
      description: "Describe the impact of the issue."
      placeholder: "Impact of the issue"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: "Steps to reproduce the issue"

  - type: markdown
    attributes:
      value: |
        # Environment Description
        
  - type: textarea
    attributes:
      label: Hardware Setup
      description: |
        Please describe your system Setup:
        - Environment: VM, bare metal
        - Hardware Specs: Cpu, Ram, Drives, etc.
        - Network: internal/external [e.g., Self, Hosted, Cloud, Peer-to-Peer, Complex VPN, etc.]
        
  - type: textarea
    attributes:
      label: Software Setup
      description: |
        Please describe what software you are using so we know what to look out for:
        - Affected Software: [e.g., Chrome, Safari, Ayon, Houdini, etc.]
        - Driver Versions

  - type: input
    attributes:
      label: User Type
      description: |
        Please describe what user this setup was made for:
        - Environment: Developer, Td, Artist, General User, Admin, etc.
        
  - type: textarea
    attributes:
      label: Additional Environment Details
      description: |
        if you have some special stuff running that we should be aware of, here is the place to tell us:
        
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What platform are you running on?
      description: |
        Please specify the operating systems you are using.
      multiple: true
      options:
        - Windows 10
        - Windows 11
        - Windows Server 2019
        - Windows Server 2022
        - Ubuntu
        - CentOS
        - Red Hat Enterprise Linux (RHEL)
        - Debian
        - Fedora
        - openSUSE
        - Arch Linux
        - Linux Mint
        - Slackware
        - Elementary OS
        - Kali Linux
        - Gentoo
        - Manjaro
        - FreeBSD
        - OpenBSD
        - NetBSD
        - Solaris
        - OpenIndiana
        - AIX (IBM)
        - macOS Monterey
        - macOS Big Sur
        - macOS Catalina
        - macOS Mojave
        - VMware ESXi (Hypervisor)
        - Microsoft Hyper-V (Hypervisor)
        - Citrix XenServer (Hypervisor)
        - Proxmox (Hypervisor)
        - Oracle VM Server
        - CoreOS
        - Ubuntu Server
        - CentOS Stream
        - Red Hat Enterprise Linux Server
        - SUSE Linux Enterprise Server

  - type: textarea
    id: suggested_fix
    attributes:
      label: "Suggested Fix"
      description: "Suggest a fix for the issue, if known."
      placeholder: "Suggested fix"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots."
      placeholder: "Additional context."

  - type: markdown
    attributes:
      value: |
        # impect assumptions

  - type: dropdown
    attributes:
      label: Impact
      description: Please specify the impact this PR has on your Operation
      multiple: true
      options:
        - No Impact
        - Low
        - Mid
        - High
        - Critical
        - Stopper

  - type: dropdown
    attributes:
      label: Assumed Complexity
      description: Please specify how complex you assume this will be
      multiple: true
      options:
        - Hours
        - Days
        - Months
        - more than 1/2 Year

  - type: dropdown
    attributes:
      label: Impact Scale
      description: Please specify how much other code/tools this might impact
      multiple: true
      options:
        - no other tool
        - one more tool 
        - a few more tools
        - an entire tool group
        - might propagate to all tools
        
  - type: textarea
    attributes:
      label: Other tools that get touched
      description: in case you put the Impact Scale to anything but None, list all the tools / repos that get affected.

  - type: checkboxes
    attributes:
      label: Is there an existing issue with this?
      description: >-
        Please search to see if an issue with the bug you encountered already exists.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Are there any labels you wish to add?
      description: Please search labels and identify those related to your bug.
      options:
        - label: I have added the relevant labels to the bug report.
          required: true
